name: Create Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  create-release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: "ubuntu-latest"
    
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Test with pytest
      run: |
        pytest .
        echo "Testing Done!"
        
    - name: Build using pyinstaller
      run: |
        pyinstaller ./src/gpkgstatus/gpkgstatus.py --clean --onefile

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            ./dist/gpkgstatus
